improve getting the current state of the current font open type feature settings (#180)
* improve getting the current state of the current font open type feature settings

* this has moved!!

* adding test

* setting windows auto save name

fix #179

* adding similar functionally for fontVariation

return a dict with the default updated with the current fontVariation
state

* add some comments

* return the fontVariation from the drawbot main tools

* adding fontVariation test

* fix 'Open in DrawBot' to work in Py3. Fixes #184

* undoing last commit, it was in the wrong branch

* typo

* updating test data

* openTypeFeatures is a dict with states
* fontVariation is a dict with a default value and the actual value
which is set

* distinguish clearly between list.... and current state settings

* listOpenTypeFeatures and listFontVariations returns the default
setting and additional related data
* setting openTypeFeatures() and fontVariations() return a dictionary
with the current state
* update test

* added test for AttributeError: 'list' object has no attribute 'update' bug

* renamed test case to be more consistent with other test cases

* return empty dict when no fea are found

* fix test failures on py2 (diff dict order)

* adding numerOfPages to the docs